[tool.poetry]
name = "your_project"
version = "0.1.0"
description = ""
authors = ["Marlin <ayushkaul@marlin.org>"]

[tool.poetry.dependencies]
python = "^3.10"
pip = "^23.0"

[tool.poetry.group.dev.dependencies]
pytest = "^6.2.4"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"